name: Deploy
on: 
  push:
    branches:
      - main
env: 
  FLY_API_TOKEN:  ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    outputs:
      app_host: ${{ steps.deploy.outputs.app_host }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
      - id: deploy
        # run: echo "::set-output name=app_host::$(flyctl status -j |jq .Hostname|tr -d '"')"
        run: echo '::set-output name=app_host::cool-water-1296.fly.dev'
      - run: echo "APP_HOST=$(flyctl status -j |jq .Hostname|tr -d '"')" |tee -a $GITHUB_ENV 